# Generated by Django 5.2.8 on 2025-12-16 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Data e hora em que o registro foi deletado. NULL significa que está ativo.', null=True, verbose_name='Data de Exclusão')),
                ('name', models.CharField(help_text='Nome da categoria de serviço', max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, help_text='Slug único para a categoria (gerado automaticamente se não fornecido)', max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada da categoria', null=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se a categoria está ativa e disponível', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('parent', models.ForeignKey(blank=True, help_text='Categoria pai para criar subcategorias (deixe em branco para categoria principal)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='services.servicecategory', verbose_name='Categoria Pai')),
            ],
            options={
                'verbose_name': 'Categoria de Serviço',
                'verbose_name_plural': 'Categorias de Serviços',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Data e hora em que o registro foi deletado. NULL significa que está ativo.', null=True, verbose_name='Data de Exclusão')),
                ('name', models.CharField(help_text='Nome do serviço', max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada do serviço', null=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o serviço está ativo e disponível', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('category', models.ForeignKey(help_text='Categoria à qual este serviço pertence', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['slug'], name='category_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['parent'], name='category_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['is_active'], name='category_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['deleted_at'], name='category_deleted_at_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category'], name='service_category_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active'], name='service_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['deleted_at'], name='service_deleted_at_idx'),
        ),
    ]
