# Generated by Django 5.2.8 on 2025-12-16 16:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Data e hora em que o registro foi deletado. NULL significa que está ativo.', null=True, verbose_name='Data de Exclusão')),
                ('rating', models.PositiveIntegerField(help_text='Nota de 1 a 5 estrelas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação')),
                ('comment', models.TextField(blank=True, help_text='Comentário opcional sobre a avaliação', null=True, verbose_name='Comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('order', models.ForeignKey(help_text='Pedido ao qual esta avaliação se refere', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orders.order', verbose_name='Pedido')),
                ('reviewed_user', models.ForeignKey(help_text='Usuário que foi avaliado', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL, verbose_name='Avaliado')),
                ('reviewer', models.ForeignKey(help_text='Usuário que fez a avaliação', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL, verbose_name='Avaliador')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order'], name='review_order_idx'), models.Index(fields=['reviewer'], name='review_reviewer_idx'), models.Index(fields=['reviewed_user'], name='review_reviewed_user_idx'), models.Index(fields=['rating'], name='review_rating_idx'), models.Index(fields=['deleted_at'], name='review_deleted_at_idx')],
                'constraints': [models.UniqueConstraint(fields=('order', 'reviewer'), name='unique_review_order_reviewer')],
            },
        ),
    ]
