# Generated by Django 5.2.8 on 2025-12-16 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Data e hora em que o registro foi deletado. NULL significa que está ativo.', null=True, verbose_name='Data de Exclusão')),
                ('name', models.CharField(help_text='Nome do plano de assinatura', max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, help_text='Slug único para o plano (gerado automaticamente se não fornecido)', max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada do plano', null=True, verbose_name='Descrição')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0.0, help_text='Preço do plano para assinatura mensal', max_digits=10, verbose_name='Preço Mensal')),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0.0, help_text='Preço do plano para assinatura anual', max_digits=10, verbose_name='Preço Anual')),
                ('features', models.JSONField(blank=True, default=dict, help_text='Recursos do plano em formato JSON (ex: {"feature1": true, "feature2": false})', verbose_name='Recursos')),
                ('max_orders_per_month', models.PositiveIntegerField(default=0, help_text='Número máximo de pedidos que o usuário pode fazer por mês (0 = ilimitado)', verbose_name='Máximo de Pedidos por Mês')),
                ('max_proposals_per_order', models.PositiveIntegerField(default=0, help_text='Número máximo de propostas que o prestador pode fazer por pedido (0 = ilimitado)', verbose_name='Máximo de Propostas por Pedido')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o plano está ativo e disponível para assinatura', verbose_name='Ativo')),
                ('is_default', models.BooleanField(default=False, help_text='Indica se este é o plano padrão atribuído a novos usuários', verbose_name='Plano Padrão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Plano de Assinatura',
                'verbose_name_plural': 'Planos de Assinatura',
                'ordering': ['price_monthly', 'name'],
                'indexes': [models.Index(fields=['slug'], name='plan_slug_idx'), models.Index(fields=['is_active'], name='plan_is_active_idx'), models.Index(fields=['is_default'], name='plan_is_default_idx'), models.Index(fields=['deleted_at'], name='plan_deleted_at_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Data e hora em que o registro foi deletado. NULL significa que está ativo.', null=True, verbose_name='Data de Exclusão')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('CANCELLED', 'Cancelada'), ('EXPIRED', 'Expirada'), ('SUSPENDED', 'Suspensa')], default='ACTIVE', help_text='Status atual da assinatura', max_length=20, verbose_name='Status')),
                ('start_date', models.DateTimeField(help_text='Data e hora de início da assinatura', verbose_name='Data de Início')),
                ('end_date', models.DateTimeField(blank=True, help_text='Data e hora de término da assinatura (NULL = sem término)', null=True, verbose_name='Data de Término')),
                ('auto_renew', models.BooleanField(default=True, help_text='Indica se a assinatura deve ser renovada automaticamente', verbose_name='Renovação Automática')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Data e hora em que a assinatura foi cancelada', null=True, verbose_name='Data de Cancelamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('plan', models.ForeignKey(help_text='Plano de assinatura', on_delete=django.db.models.deletion.PROTECT, related_name='user_subscriptions', to='subscriptions.subscriptionplan', verbose_name='Plano')),
                ('user', models.ForeignKey(help_text='Usuário que possui esta assinatura', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Assinatura de Usuário',
                'verbose_name_plural': 'Assinaturas de Usuários',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Data e hora em que o registro foi deletado. NULL significa que está ativo.', null=True, verbose_name='Data de Exclusão')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Valor do pagamento', max_digits=10, verbose_name='Valor')),
                ('payment_method', models.CharField(blank=True, help_text='Método utilizado para o pagamento (ex: credit_card, pix, boleto)', max_length=50, null=True, verbose_name='Método de Pagamento')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago'), ('FAILED', 'Falhou'), ('REFUNDED', 'Reembolsado')], default='PENDING', help_text='Status atual do pagamento', max_length=20, verbose_name='Status do Pagamento')),
                ('transaction_id', models.CharField(blank=True, help_text='ID único da transação no gateway de pagamento', max_length=255, null=True, unique=True, verbose_name='ID da Transação')),
                ('payment_date', models.DateTimeField(blank=True, help_text='Data e hora em que o pagamento foi realizado', null=True, verbose_name='Data de Pagamento')),
                ('due_date', models.DateTimeField(help_text='Data e hora de vencimento do pagamento', verbose_name='Data de Vencimento')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Informações adicionais do pagamento em formato JSON', verbose_name='Metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('subscription', models.ForeignKey(help_text='Assinatura à qual este pagamento pertence', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.usersubscription', verbose_name='Assinatura')),
            ],
            options={
                'verbose_name': 'Pagamento de Assinatura',
                'verbose_name_plural': 'Pagamentos de Assinatura',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user'], name='subscription_user_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['plan'], name='subscription_plan_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['status'], name='subscription_status_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['end_date'], name='subscription_end_date_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['deleted_at'], name='subscription_deleted_at_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionpayment',
            index=models.Index(fields=['subscription'], name='payment_subscription_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionpayment',
            index=models.Index(fields=['payment_status'], name='payment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionpayment',
            index=models.Index(fields=['due_date'], name='payment_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionpayment',
            index=models.Index(fields=['transaction_id'], name='payment_transaction_id_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionpayment',
            index=models.Index(fields=['deleted_at'], name='payment_deleted_at_idx'),
        ),
    ]
