# Generated by Django 5.2.8 on 2025-12-16 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Data e hora em que o registro foi deletado. NULL significa que está ativo.', null=True, verbose_name='Data de Exclusão')),
                ('token', models.CharField(help_text='Token único do dispositivo para notificações push (FCM)', max_length=255, unique=True, verbose_name='Token')),
                ('device_type', models.CharField(choices=[('IOS', 'iOS'), ('ANDROID', 'Android'), ('WEB', 'Web')], help_text='Tipo do dispositivo: iOS, Android ou Web', max_length=20, verbose_name='Tipo de Dispositivo')),
                ('device_id', models.CharField(blank=True, help_text='ID único do dispositivo (opcional)', max_length=255, null=True, verbose_name='ID do Dispositivo')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o token está ativo e pode receber notificações', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('user', models.ForeignKey(help_text='Usuário proprietário do dispositivo', on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Token de Dispositivo',
                'verbose_name_plural': 'Tokens de Dispositivos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='device_token_user_idx'), models.Index(fields=['token'], name='device_token_token_idx'), models.Index(fields=['device_type'], name='device_token_type_idx'), models.Index(fields=['is_active'], name='device_token_active_idx'), models.Index(fields=['deleted_at'], name='device_token_deleted_idx')],
            },
        ),
    ]
