# Generated by Django 5.2.8 on 2025-12-16 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Data e hora em que o registro foi deletado. NULL significa que está ativo.', null=True, verbose_name='Data de Exclusão')),
                ('address', models.CharField(blank=True, help_text='Endereço completo do cliente', max_length=255, null=True, verbose_name='Endereço')),
                ('city', models.CharField(blank=True, help_text='Cidade do cliente', max_length=100, null=True, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, help_text='Estado (UF) do cliente', max_length=2, null=True, verbose_name='Estado')),
                ('zip_code', models.CharField(blank=True, help_text='CEP do cliente', max_length=10, null=True, verbose_name='CEP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('user', models.OneToOneField(help_text='Usuário associado a este perfil de cliente', on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Cliente',
                'verbose_name_plural': 'Perfis de Clientes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['city', 'state'], name='client_location_idx'), models.Index(fields=['deleted_at'], name='client_deleted_at_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Data e hora em que o registro foi deletado. NULL significa que está ativo.', null=True, verbose_name='Data de Exclusão')),
                ('bio', models.TextField(blank=True, help_text='Biografia ou descrição do prestador', null=True, verbose_name='Biografia')),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0.0, help_text='Média de avaliações recebidas (0.00 a 5.00)', max_digits=3, verbose_name='Avaliação Média')),
                ('total_reviews', models.PositiveIntegerField(default=0, help_text='Número total de avaliações recebidas', verbose_name='Total de Avaliações')),
                ('total_orders_completed', models.PositiveIntegerField(default=0, help_text='Número total de pedidos completados', verbose_name='Pedidos Completados')),
                ('is_verified', models.BooleanField(default=False, help_text='Indica se o prestador foi verificado pela plataforma', verbose_name='Verificado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('user', models.OneToOneField(help_text='Usuário associado a este perfil de prestador', on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Prestador',
                'verbose_name_plural': 'Perfis de Prestadores',
                'ordering': ['-rating_avg', '-total_orders_completed'],
                'indexes': [models.Index(fields=['rating_avg'], name='provider_rating_avg_idx'), models.Index(fields=['is_verified'], name='provider_is_verified_idx'), models.Index(fields=['deleted_at'], name='provider_deleted_at_idx')],
            },
        ),
    ]
