# Generated by Django 5.2.8 on 2025-12-16 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Data e hora em que o registro foi deletado. NULL significa que está ativo.', null=True, verbose_name='Data de Exclusão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('last_message_at', models.DateTimeField(blank=True, help_text='Data e hora da última mensagem enviada na sala', null=True, verbose_name='Última Mensagem')),
                ('client', models.ForeignKey(help_text='Cliente participante da conversa', on_delete=django.db.models.deletion.CASCADE, related_name='client_chat_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('order', models.ForeignKey(help_text='Pedido relacionado a esta sala de chat', on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='orders.order', verbose_name='Pedido')),
                ('provider', models.ForeignKey(help_text='Prestador participante da conversa', on_delete=django.db.models.deletion.CASCADE, related_name='provider_chat_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Prestador')),
            ],
            options={
                'verbose_name': 'Sala de Chat',
                'verbose_name_plural': 'Salas de Chat',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Data e hora em que o registro foi deletado. NULL significa que está ativo.', null=True, verbose_name='Data de Exclusão')),
                ('content', models.TextField(help_text='Conteúdo da mensagem', verbose_name='Conteúdo')),
                ('message_type', models.CharField(choices=[('TEXT', 'Texto'), ('IMAGE', 'Imagem'), ('FILE', 'Arquivo'), ('SYSTEM', 'Sistema')], default='TEXT', help_text='Tipo da mensagem: texto, imagem, arquivo ou sistema', max_length=20, verbose_name='Tipo de Mensagem')),
                ('is_read', models.BooleanField(default=False, help_text='Indica se a mensagem foi lida pelo destinatário', verbose_name='Lida')),
                ('read_at', models.DateTimeField(blank=True, help_text='Data e hora em que a mensagem foi lida', null=True, verbose_name='Data de Leitura')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('room', models.ForeignKey(help_text='Sala de chat à qual esta mensagem pertence', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom', verbose_name='Sala de Chat')),
                ('sender', models.ForeignKey(help_text='Usuário que enviou a mensagem', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Remetente')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['order'], name='chatroom_order_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['client'], name='chatroom_client_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['provider'], name='chatroom_provider_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['last_message_at'], name='chatroom_last_message_at_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['deleted_at'], name='chatroom_deleted_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(fields=('order', 'client', 'provider'), name='unique_chatroom_order_client_provider'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room'], name='message_room_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='message_sender_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='message_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='message_is_read_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['deleted_at'], name='message_deleted_at_idx'),
        ),
    ]
