# Generated by Django 5.2.8 on 2025-12-16 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_clientprofile_providerprofile'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Data e hora em que o registro foi deletado. NULL significa que está ativo.', null=True, verbose_name='Data de Exclusão')),
                ('title', models.CharField(help_text='Título do pedido', max_length=200, verbose_name='Título')),
                ('description', models.TextField(help_text='Descrição detalhada do pedido', verbose_name='Descrição')),
                ('budget_min', models.DecimalField(decimal_places=2, help_text='Valor mínimo do orçamento', max_digits=10, verbose_name='Orçamento Mínimo')),
                ('budget_max', models.DecimalField(decimal_places=2, help_text='Valor máximo do orçamento', max_digits=10, verbose_name='Orçamento Máximo')),
                ('deadline', models.DateTimeField(help_text='Data limite para conclusão do serviço', verbose_name='Prazo')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('ACCEPTED', 'Aceito'), ('IN_PROGRESS', 'Em Progresso'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='PENDING', help_text='Status atual do pedido', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('client', models.ForeignKey(help_text='Cliente que fez o pedido', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.clientprofile', verbose_name='Cliente')),
                ('service', models.ForeignKey(help_text='Serviço solicitado', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='services.service', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Data e hora em que o registro foi deletado. NULL significa que está ativo.', null=True, verbose_name='Data de Exclusão')),
                ('message', models.TextField(help_text='Mensagem explicativa da proposta', verbose_name='Mensagem')),
                ('price', models.DecimalField(decimal_places=2, help_text='Preço proposto para o serviço', max_digits=10, verbose_name='Preço')),
                ('estimated_days', models.PositiveIntegerField(help_text='Número de dias estimados para conclusão do serviço', verbose_name='Prazo Estimado (dias)')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('ACCEPTED', 'Aceita'), ('DECLINED', 'Recusada'), ('EXPIRED', 'Expirada')], default='PENDING', help_text='Status atual da proposta', max_length=20, verbose_name='Status')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Data e hora em que a proposta expira (opcional)', null=True, verbose_name='Data de Expiração')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('order', models.ForeignKey(help_text='Pedido ao qual esta proposta se refere', on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='orders.order', verbose_name='Pedido')),
                ('provider', models.ForeignKey(help_text='Prestador que fez a proposta', on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='accounts.providerprofile', verbose_name='Prestador')),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client'], name='order_client_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['service'], name='order_service_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['deadline'], name='order_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['deleted_at'], name='order_deleted_at_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['order'], name='proposal_order_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['provider'], name='proposal_provider_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['status'], name='proposal_status_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['expires_at'], name='proposal_expires_at_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['deleted_at'], name='proposal_deleted_at_idx'),
        ),
    ]
