# Generated by Django 5.2.8 on 2025-12-16 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Data e hora em que o registro foi deletado. NULL significa que está ativo.', null=True, verbose_name='Data de Exclusão')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Valor do pagamento', max_digits=10, verbose_name='Valor')),
                ('payment_method', models.CharField(blank=True, help_text='Método utilizado para o pagamento (ex: credit_card, pix, boleto)', max_length=50, null=True, verbose_name='Método de Pagamento')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago'), ('FAILED', 'Falhou'), ('REFUNDED', 'Reembolsado')], default='PENDING', help_text='Status atual do pagamento', max_length=20, verbose_name='Status do Pagamento')),
                ('transaction_id', models.CharField(blank=True, help_text='ID único da transação no gateway de pagamento', max_length=255, null=True, unique=True, verbose_name='ID da Transação')),
                ('payment_date', models.DateTimeField(blank=True, help_text='Data e hora em que o pagamento foi realizado', null=True, verbose_name='Data de Pagamento')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Informações adicionais do pagamento em formato JSON (dados do gateway, etc.)', verbose_name='Metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('order', models.ForeignKey(help_text='Pedido ao qual este pagamento se refere', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='Pedido')),
                ('proposal', models.ForeignKey(help_text='Proposta aceita que gerou este pagamento', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.proposal', verbose_name='Proposta')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order'], name='svc_payment_order_idx'), models.Index(fields=['proposal'], name='svc_payment_proposal_idx'), models.Index(fields=['payment_status'], name='svc_payment_status_idx'), models.Index(fields=['transaction_id'], name='svc_payment_txn_id_idx'), models.Index(fields=['payment_date'], name='svc_payment_date_idx'), models.Index(fields=['deleted_at'], name='svc_payment_deleted_idx')],
            },
        ),
    ]
