# Generated by Django 5.2.8 on 2025-12-16 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Data e hora em que o registro foi deletado. NULL significa que está ativo.', null=True, verbose_name='Data de Exclusão')),
                ('action_type', models.CharField(help_text='Tipo da ação realizada (ex: USER_DELETE, ORDER_CANCEL, PLAN_UPDATE)', max_length=100, verbose_name='Tipo de Ação')),
                ('target_model', models.CharField(blank=True, help_text='Nome do modelo Django afetado pela ação (ex: User, Order)', max_length=100, null=True, verbose_name='Modelo Alvo')),
                ('target_id', models.BigIntegerField(blank=True, help_text='ID do objeto afetado pela ação', null=True, verbose_name='ID do Alvo')),
                ('description', models.TextField(help_text='Descrição detalhada da ação realizada', verbose_name='Descrição')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Informações adicionais da ação em formato JSON', verbose_name='Metadados')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Endereço IP de onde a ação foi realizada', null=True, verbose_name='Endereço IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('admin_user', models.ForeignKey(help_text='Usuário administrador que realizou a ação', on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
            ],
            options={
                'verbose_name': 'Ação Administrativa',
                'verbose_name_plural': 'Ações Administrativas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin_user'], name='admin_action_user_idx'), models.Index(fields=['action_type'], name='admin_action_type_idx'), models.Index(fields=['target_model', 'target_id'], name='admin_action_target_idx'), models.Index(fields=['created_at'], name='admin_action_created_at_idx'), models.Index(fields=['deleted_at'], name='admin_action_deleted_at_idx')],
            },
        ),
    ]
